version: "2"

services:
  fluentd:
    image: fluent/fluentd:latest
    ports:
      - "24224:24224"
    environment:
      - 'FLUENTD_CONF=fluentd.conf'
    volumes:
      - ./log:/fluentd/log
      - ./conf:/fluentd/etc
