version: "2"

services:
  fluentd:
    container_name: fluentd
    build: ./plugins
    ports:
      - "24224:24224"
    environment:
      FLUENTD_CONF: fluentd.conf
      S3_BUCKET_NAME: my-server-logs
      FLUENT_UID: 0
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    volumes:
      - ./log:/fluentd/log
      - ./conf:/fluentd/etc
      - /var/log:/host/var/log
