version: '2'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /tmp/metabase.db
    volumes:
      - ./data:/tmp/
    logging:
      driver: fluentd
      options:
        tag: "docker.metabase.{{.Name}}"
networks:
  default:
    external:
      name: bitool-db
