host:
  webapi: docker.serinuntius.com
  reverse_proxy_suffix: .serinuntius.com

listen:
  # listen address
  # default is only listen from localhost
  foreign_address: 0.0.0.0

  # listen port and reverse proxy port
  http:
    # listen 8080 and transport to container's 5000 port
    - listen: 30000
      target: 3000

  # not implemented
  # we recommend to use frontend http(like nginx) to SSL termination
  # HTTPS:
  #   - 443

docker:
  # if you use docker through http, specify like "http://localhost:4243"
  endpoint: unix:///var/run/docker.sock
  docker_networks:
  - name: webproxy
  - name: mysql57

  host_config:
    AutoRemove: true

storage:
  datadir: ./data
  htmldir: ./html

parameters:
  - name: branch
    env: GIT_BRANCH
    rule: ""
    required: true

  - name: host
    env: VIRTUAL_HOST
    required: true

  - name: port
    env: VIRTUAL_PORT
    required: true

  - name: letsencrypt_host
    env: LETSENCRYPT_HOST
    required: true

  - name: letsencrypt_email
    env: LETSENCRYPT_EMAIL
    required: true

env_file: ./.env
