version: '2'
services:
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    logging:
      driver: fluentd
      options:
        tag: "docker.redash-server.{{.Name}}"
    restart: always
  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    logging:
      driver: fluentd
      options:
        tag: "docker.redash-worker.{{.Name}}"
    restart: always
  redis:
    image: redis:3.0-alpine
    logging:
      driver: fluentd
      options:
        tag: "docker.redash-redis.{{.Name}}"
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
    logging:
      driver: fluentd
      options:
        tag: "docker.redash-postgres.{{.Name}}"
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - server
    links:
      - server:redash
    logging:
      driver: fluentd
      options:
        tag: "docker.redash-nginx.{{.Name}}"
    restart: always
networks:
 default:
   external:
     name: bitool-db
