version: '2.3'
services:
    tensorflow:
          runtime: nvidia
          build:
            dockerfile: Dockerfile.gpu
            context: .
          command: jupyter notebook --allow-root
          container_name: tensorflow
          ports:
            - "8888:8888"
          volumes:
            - "$PWD/notebooks:/workdir"
          working_dir: /workdir
          restart: always
          environment:
            - "VIRTUAL_HOST=jupyter.serinuntius.com"
            - "LETSENCRYPT_HOST=serinuntius.com"
            - "LETSENCRYPT_EMAIL=wasab1gj@gmail.com"
            - "VIRTUAL_PORT=8888"
networks:
  default:
    external:
      name: webproxy
