version: '2'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret 
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
networks:
  default:
    external:
      name: bitool-db
